---
title: "Team meeting"
date: "2023-03-14"
---

## Agenda (3/14/2023)

1. Meeting with Overlay on Friday, 3/17, 1pm.
    a. Meeting video link: <https://meetings.vonage.com/924821612>
    a. Friday agenda:
        1. demo tool set.
            a. Show examples of PDF, HTML and PPTX
            a. discuss pros and cons of each
        1. ask questions:
            a. what output is preferred? PDF? PPTX?
            a. data were mentioned, do you have spreadsheet or other source?
            a. other templates beside Bison?
1. Review of activities
    a. Install software (see previous agenda)
    a. Discuss team skills and capabililties
        1. Anyone with python coding skills?
    a. Discuss project needs
        1. Overlay (ssgvip-quarto-overlay-finreport)
            a. create PPT template and demo example with appropriatly styled fonts, etc.
            a. Create Reveal/HTML template and example
            a. Create Beamer template and example
        1. CMSC (ssgvip-quarto-cmsc-courses)
            a. Quarto web site with links to existing docs
            a. Create QMD for each PDF
            a. Incorporate data from XLSX.
        1. CMSC 475 (ssgvip-quarto-sandbox)
            a. Create into presentation to quarto
            a. Discuss getting started
            a. Include figures that show inputs / outputs
            a. (Generally, create presentations that teach quarto!)
1. Assignment of tasks
    a. Overlay PPTX lead - PPTX template creator, dive into style guide, edit/update template and generate document that looks like their example
    a. Overlay Reveal/HTML lead - must learn HTML/Reveal templating (CSS is a useful skill!)
    a. Overlay BEAMER lead - must learn LaTeX, and create custom style. (difficult!)
    a. CMSC lead - Create QMD files for each class. Lots of cut and paste.

    - Zach:
    - Inho:
    - Nitin:
    - Moses:
    - Taiasia:


## Agenda (3/1/2023)

1.	People intros
1.	Project intros: the tool set and our 3 case studies,
1.	Assigning tasks and talking about hours,
1.	Introducing you to the command line terminal. This is where our project work will be conducted.
1.	Installing tool set and related software:
    a.	choco(PC), or homebrew (Mac),
    a.	git,
    a.	vscode,
    a.	quarto,
    a.	pyenv,
    a.	poetry,
    a.	python
1.	Testing software and creating first quarto document.
1.	The four project repositories: <https://github.com/orgs/ssgvip/repositories>
    a.	[CS department (syllabi and outlines, web and PDF)](https://github.com/ssgvip/ssgvip-quarto-cmsc-courses)
    a.	[CMSC 508 (class materials, web)](https://github.com/lowkeylabs/cmsc475-202320-materials)
    a.	[Overlay (financial reporting, PPT and PDF)](https://github.com/ssgvip/ssgvip-quarto-overlay-finreport)
    a.  [Project admin sandbox](https://github.com/ssgvip/ssgvip-quarto-sandbox)


## Concepts and skills to learn

- Basic document creation
- Writing to different output formats
- Themeing for different output formats

At the end of this project, team members will be well versed in using quarto, generating quarto documents and websites, creating quarto themes, and designing quarto work flows.

Team members will also be familiar with GIT and GITHUB, and maybe Python programming.

## Case studies

Skills will be refined through focus on three specific case studies.

1. Individual course web site - The team will develop consistent themes that can be applied to a CMSC course for all the different course materials including outline, syllabus, lecture notes, homework assignments, POGILS, and a wrapper web site. This case study will output in DOC, HTML, PPTX and PDF formats.

1. CMSC-wide course site - The team will create a CMSC-wide web site that lists all courses taught by CMSC and provides links to course descriptions, syllabi and outlines. The team will also create a cross-course map of topics and courses, so that faculty and students can quickly see what topics are taught in what courses. This case study will output in web site format.

1. Corporate reporting - The team will convert an existing corporate report into a quarto-created document, creating "variables" at the topic of the document to permit changing of data to include in figures, and changing the underlying document theme to meet the needs of different customers. This case study will output in PPTX and PDF.

1. Project administration - The team will use quarto to document and manage this project. This case study will output in HTML and web site format.

## Schedules and meetings

1. Next meeting with *Overlay Shares* is Wednesday, March 14 at 1pm via "Vonage" service.
1. Spring break is next week.

1. Best way to stay in contact?  DISCORD?
1. Best time to meet as a group?
1. Best way to distribute work?
1. Should we create a schedule mapping out the next five weeks?

## Team members and Bios

Resumes for team members can be found in [this PDF](assets/team-member-resumes.pdf).


Taiasia Napier - 

Inho Park - Inho is a junior student currently pursuing BFA in Graphic Design at VCUarts. He was born in South Korea, and first came to America in 2018 to study at VCU. In 2019, he left VCU to serve in the Korean military. There, he served as a human resource specialist in the US-Korea liaison office and later as a team leader for 18 soldiers in US-Korea Combined 2nd Infantry Division.After he was discharged in 2021, he returned to VCU and has been actively building his career as a UX/UI designer in the digital product innovation field. Now he is leading a collaborative software consulting project for The Routing Company and VCU Parking & Transportation to improve software solution for VCU's student transit service, VCU RamSafe.  

Nitin Kanuri - Nitin Kanuri is a freshman student studying business management on the predental track. Nitin was born and raised in the Richmond area and is familiar with VCU. Nitin's research interests include studying the applications of machine learning on dental specialties such as oral and maxillofacial surgery and oral and maxillofacial radiology. Nitin is currently in the eight year guaranteed admissions program for dentistry, and hopes to apply to the VCU Oral and Maxillofacial Surgery residency at the completion of his eight year program. Nitin's linkedin is: [LinkedIn](www.linkedin.com/in/nitinkanuri)

Zach McDonough - As a junior Computer Science student at Virginia Commonwealth University, I am an active solution seeker with a strong passion for technology and a solid foundation in programming languages such as Java, HTML, CSS, C#, and Python. I have been a part of two internships: one at Klockner Pentaplast, where I helped update machines to Windows 10, resolve network abnormalities, and ensure the security and privacy of networks and computer systems; and another at VCU, where I collaborated with a team to develop an application that determined the political affiliation of Twitter users using Python and jQuery. I am proficient in Spanish and have an Advanced Diploma from Hermitage High School, as well as an ACE Center certification in Web Development and Programming. In 2018, I organized and led HCPS Hour of Code activities for hundreds of Henrico middle school students from five schools, encouraging their interest in the field of computer science. I also assisted in facilitating rotation groups for Dia de Ciencias day 2019 to introduce the wonders of Computer Science to Spanish speaking students in the Chesterfield County School District.

Moses Farley - Moses is a post baccalaureate student studying Computer Science. He earned his bachelor's degree in economics from William and Mary and is interested in the intersection between computer science, machine learning, and environmental science/environmental economics.

William Benton - 

John Leonard - Dr. Leonard is a professor of computer science and co-founder of the Software for Social Good VIP. Dr. Leonard teaches classes in databases (back end) and user interfaces (front and and API development). Dr. Leonard first taught a class in FORTRAN at Irvine Valley College (Orange County, CA) in 1985. He received his BS, MS and PhD degrees from the University of California, Irvine in 1993, 1986 and 1991 respectively. Dr. Leonard joined the faculty of the School of Civil and Environmental Engineering at Georgia Institute of Technology in 1993, conducting research and teaching in traffic and transportation systems modeling, and serving as Associate Dean for Finance and Administration in their College of Engineering. Dr. Leonard joined the faculty of Computer Science at VCU in 2016 and served as Executive Dean of the College of Engineering for six years.
