project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - index.qmd
          - index.qmd
      - section: "Layout"
        contents:
          - index.qmd
          - index.qmd
          - index.qmd

format:
  html:
    theme: johntheme.scss
    toc: true
    